/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javafx.stage.FileChooser;
import javafx.stage.FileChooser.ExtensionFilter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dexter Sam
 */
public class GLibrary2 extends javax.swing.JFrame {

    /**
     * Creates new form GLibrary
     */
    boolean [] inside ={false,false,false,false,false};
    public GLibrary2() {
         initComponents();
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("steam.png")));
         Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         if(!inside[0])
         {
             insidecover.setVisible(false);
             insidegenre.setVisible(false);
             insidelabel.setVisible(false);
             insidelogo.setVisible(false);
             insideplay.setVisible(false);
             insidevalue.setVisible(false);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        insidelogo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        insidevalue = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        insidecover = new javax.swing.JLabel();
        insidelabel = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        insidegenre = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        insideplay = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        searchbar = new javax.swing.JTextField();
        exit = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 599));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(650, 3460));
        jPanel4.setPreferredSize(new java.awt.Dimension(650, 3560));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Need For Speed : Most Wanted");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1050, 230, 40));

        insidelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        insidelogo.setText("jLabel8");
        jPanel4.add(insidelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 3130, 50, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Race,Car,Action");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1180, 220, -1));

        insidevalue.setBackground(new java.awt.Color(255, 255, 255));
        insidevalue.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        insidevalue.setForeground(new java.awt.Color(255, 255, 255));
        insidevalue.setText("Free");
        jPanel4.add(insidevalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 3230, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/games/07035af9-a785-4eae-b4c3-4455b89b6b5b.jpg"))); // NOI18N
        jLabel23.setText("jLabel12");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 340, 170));

        jLabel24.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Road Rash");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 170, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel25.setText("jLabel8");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 50, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Race,Arcade,Retro");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 220, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Free");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/games/orphanncover.jpg"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 340, 220));

        jLabel29.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Alien Shooter 2");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 190, 40));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel30.setText("jLabel8");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 50, 50));

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Action,TPS,Shooting");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 220, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Free");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/games/kof.png"))); // NOI18N
        jLabel33.setText("jLabel33");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 350, 190));

        jLabel34.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Orphan");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 190, 40));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel35.setText("jLabel8");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 50, 50));

        jLabel36.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Puzzle,Strategy");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 220, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Free");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/games/nfscover.jpg"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1060, 370, 200));

        jLabel39.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Kings Of fighter 97");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 190, 40));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel40.setText("jLabel8");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 850, 50, 50));

        jLabel41.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Fighting,Action");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 920, 220, -1));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Free");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 960, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 2690, 70, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 80, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel8.setText("jLabel6");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 80, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 70, 120));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel10.setText("jLabel6");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 870, 70, 90));

        insidecover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/insidecover.jpg"))); // NOI18N
        insidecover.setText("jLabel38");
        jPanel4.add(insidecover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 3100, 400, 190));

        insidelabel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        insidelabel.setForeground(new java.awt.Color(255, 255, 255));
        insidelabel.setText("Inside");
        jPanel4.add(insidelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 3080, 190, 40));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel45.setText("jLabel8");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1110, 50, 50));

        insidegenre.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        insidegenre.setForeground(new java.awt.Color(255, 255, 255));
        insidegenre.setText("Puzzle,Adventure,Thriller");
        jPanel4.add(insidegenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 3190, 220, -1));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Free");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1220, -1, -1));

        insideplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        insideplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insideplayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insideplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insideplayMouseExited(evt);
            }
        });
        jPanel4.add(insideplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 3130, 70, 100));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/games/roadz.png"))); // NOI18N
        jLabel18.setText("jLabel6");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 60, 330, 190));

        jLabel48.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Sekiro Shadows Die Twice");
        jPanel4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2850, 190, 40));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel49.setText("jLabel8");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 2900, 50, 50));

        jLabel50.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Action,Adventure,Shooting");
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1710, 220, -1));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Free");
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 3020, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/sekiromain.jpg"))); // NOI18N
        jLabel52.setText("jLabel38");
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2860, 410, 200));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 2890, 70, 100));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/bfcover2.png"))); // NOI18N
        jLabel53.setText("jLabel38");
        jPanel4.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1340, 360, 180));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/batman arakham.jpg"))); // NOI18N
        jLabel54.setText("jLabel38");
        jPanel4.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1600, 390, 190));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/wwe2k.jpg"))); // NOI18N
        jLabel55.setText("jLabel38");
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1840, 390, 190));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/statedecaycover.jpg"))); // NOI18N
        jLabel56.setText("jLabel38");
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2330, 390, 210));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/niohcover.jpg"))); // NOI18N
        jLabel57.setText("jLabel38");
        jPanel4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2070, 390, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1430, 70, 90));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1680, 70, 90));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1920, 70, 90));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel43MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel43MouseExited(evt);
            }
        });
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 2150, 70, 90));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png"))); // NOI18N
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel44MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel44MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel44MouseExited(evt);
            }
        });
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 2430, 70, 90));

        jLabel58.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Battlefield 1");
        jPanel4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1330, 190, 40));

        jLabel59.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Batman Arkham Knight");
        jPanel4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1590, 190, 40));

        jLabel60.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("WWE 2K17");
        jPanel4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1830, 190, 40));

        jLabel61.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("NIOH");
        jPanel4.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2060, 190, 40));

        jLabel62.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("State OF Decay 2");
        jPanel4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2320, 190, 40));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel63.setText("jLabel8");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1880, 50, 50));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel64.setText("jLabel8");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2170, 50, 50));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel65.setText("jLabel8");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1380, 50, 50));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel66.setText("jLabel8");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 1640, 50, 50));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel67.setText("jLabel8");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 2380, 50, 50));

        jLabel68.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Sports,Fight,Wrestling");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1950, 220, -1));

        jLabel69.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Action,Adventure,RPG");
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2130, 220, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Shooting,Action Horror");
        jPanel4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2450, 220, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Open World,Action ,Adventure,RPG");
        jPanel4.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2970, 220, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Shooting,Action,War");
        jPanel4.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1450, 220, -1));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Free");
        jPanel4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1490, -1, -1));

        jLabel74.setBackground(new java.awt.Color(255, 255, 255));
        jLabel74.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Free");
        jPanel4.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1770, -1, -1));

        jLabel75.setBackground(new java.awt.Color(255, 255, 255));
        jLabel75.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Free");
        jPanel4.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2000, -1, -1));

        jLabel76.setBackground(new java.awt.Color(255, 255, 255));
        jLabel76.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Free");
        jPanel4.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2240, -1, -1));

        jLabel77.setBackground(new java.awt.Color(255, 255, 255));
        jLabel77.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Free");
        jPanel4.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2500, -1, -1));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/fc5cover.jpg"))); // NOI18N
        jLabel78.setText("jLabel38");
        jPanel4.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2600, 400, 200));

        jLabel79.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Farcry 5");
        jPanel4.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2590, 190, 40));

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/windows icon.png"))); // NOI18N
        jLabel80.setText("jLabel8");
        jPanel4.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 2640, 50, 50));

        jLabel81.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Open World,Action ,Adventure");
        jPanel4.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2710, 220, -1));

        jLabel82.setBackground(new java.awt.Color(255, 255, 255));
        jLabel82.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("Free");
        jPanel4.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 2770, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png"))); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel46MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel46MouseExited(evt);
            }
        });
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1130, 70, 100));

        jScrollPane1.setViewportView(jPanel4);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 850, 570));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/razer_ripsaw_hd_gallery_08.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setIconTextGap(0);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 60, 1030, 570));

        kGradientPanel1.setkEndColor(new java.awt.Color(158, 3, 97));
        kGradientPanel1.setkStartColor(new java.awt.Color(249, 71, 33));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchbar.setBackground(new java.awt.Color(158, 55, 117));
        searchbar.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        searchbar.setForeground(new java.awt.Color(255, 255, 255));
        searchbar.setBorder(null);
        kGradientPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 190, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        exit.setText("jLabel8");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        kGradientPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });
        kGradientPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 30, 40));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 190, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/adobecc2.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/plus2.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/minus2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1030, 60));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 51, 51));
        kGradientPanel2.setkStartColor(new java.awt.Color(158, 3, 97));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Profile");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chat");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/stadia banner23.png"))); // NOI18N
        kGradientPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
         jLabel1.setForeground(new java.awt.Color(103,193,245));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(103,193,245));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setForeground(new java.awt.Color(103,193,245));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel3.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel4.setForeground(new java.awt.Color(103,193,245));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel4.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
       jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Roadrash injust =new Roadrash();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
         jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        alienshooter injust =new alienshooter();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        orphan injust =new orphan();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
       
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
           jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        kof dogs =new kof();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
           jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel10MouseExited

    private void insideplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insideplayMouseClicked
        // TODO add your handling code here:
        inside witch =new inside();
        witch.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_insideplayMouseClicked

    private void insideplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insideplayMouseEntered
        // TODO add your handling code here:
           insideplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_insideplayMouseEntered

    private void insideplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insideplayMouseExited
        // TODO add your handling code here:
        insideplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_insideplayMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        farcary5 injust =new farcary5();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
           jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        String game = searchbar.getText();
        if(game.contains("injustice")|| game.contains("injustice 2"))
        {
        Injustice2 injust =new Injustice2();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("dota")|| game.contains("dota 2"))
        {
        Dota2 injust =new Dota2();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("deux")|| game.contains("deus ex"))
        {
        DeusEx injust =new DeusEx();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("watchdogs")|| game.contains("watchdogs 2"))
        {
        Watchdogs2 injust =new Watchdogs2();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("witcher")|| game.contains("witcher 3"))
        {
        Witcher3 injust =new Witcher3();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("star")|| game.contains("starwars"))
        {
        Starwar injust =new Starwar();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        if(game.contains("alien")|| game.contains("alien shooter"))
        {
        orphan injust =new orphan();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        }
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_20px.png")));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png")));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Profile injust =new Profile();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        messenger injust =new messenger();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_30px.png")));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png")));
    }//GEN-LAST:event_exitMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
         GLibrary game =new GLibrary();
        game.setVisible(true);
        WindowEvent closed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closed);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        sekiro injust =new sekiro();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
            jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        JFileChooser choose=new JFileChooser() ; 
        choose.showOpenDialog(null);
        File f= choose.getSelectedFile();
        String filename= f.getAbsolutePath();
        if(!filename.contains("exe"))
            JOptionPane.showMessageDialog(null,"Invalid Exe File");
        else
        {    
        int input = JOptionPane.showConfirmDialog(null, "Add Game to The Library?");
        if(input==0)
        {
             insidecover.setVisible(true);
             insidegenre.setVisible(true);
             insidelabel.setVisible(true);
             insidelogo.setVisible(true);
             insideplay.setVisible(true);
             insidevalue.setVisible(true);
        }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove the game?");
        if(input==0)
        { 
             insidecover.setVisible(false);
             insidegenre.setVisible(false);
             insidelabel.setVisible(false);
             insidelogo.setVisible(false);
             insideplay.setVisible(false);
             insidevalue.setVisible(false);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Add Game to The Library?");
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        GLibrary2 game =new GLibrary2();
        game.setVisible(true);
        WindowEvent closed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closed);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        battlefield dogs =new battlefield();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
         jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        batman dogs =new batman();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
         jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        // TODO add your handling code here:
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        wwe dogs =new wwe();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
         jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here:
        nioh dogs =new nioh();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jLabel43MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseEntered
        // TODO add your handling code here:
         jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel43MouseEntered

    private void jLabel43MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseExited
        // TODO add your handling code here:
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel43MouseExited

    private void jLabel44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseClicked
        // TODO add your handling code here:
         stateofdecay injust =new   stateofdecay();
        injust.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel44MouseClicked

    private void jLabel44MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseEntered
        // TODO add your handling code here:
         jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss3.png")));
    }//GEN-LAST:event_jLabel44MouseEntered

    private void jLabel44MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseExited
        // TODO add your handling code here:
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/downloadiconsss2.png")));
    }//GEN-LAST:event_jLabel44MouseExited

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        nfs dogs =new nfs();
        dogs.setVisible(true);
        WindowEvent clossed = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(clossed);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jLabel46MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseEntered
        // TODO add your handling code here:
         jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz3.png")));
    }//GEN-LAST:event_jLabel46MouseEntered

    private void jLabel46MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseExited
        // TODO add your handling code here:
         jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/playiconz2.png")));
    }//GEN-LAST:event_jLabel46MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
           jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/plus3.png")));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
           jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/plus2.png")));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
         jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/minus3.png")));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
         jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/minus2.png")));
    }//GEN-LAST:event_jLabel14MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GLibrary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GLibrary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GLibrary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GLibrary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GLibrary2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel insidecover;
    private javax.swing.JLabel insidegenre;
    private javax.swing.JLabel insidelabel;
    private javax.swing.JLabel insidelogo;
    private javax.swing.JLabel insideplay;
    private javax.swing.JLabel insidevalue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField searchbar;
    // End of variables declaration//GEN-END:variables
}
